# Generated by Django 5.1.3 on 2024-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_students_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('membership', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
